---
- name: Deploy Docker Image to Container
  hosts: demo

  tasks:
    - name: Pull Docker Image
      docker_image:
        name: jayantmukundam/calc_with_devops
        tag: latest
        source: pull

    - name: Create & Start Calculator Docker Container
      docker_container:
        name: calculator-using-devops
        image: jayantmukundam/calc_with_devops
        state: started
        interactive: yes
